baseURL = "https://flurry-l.github.io/hugo-moments"
languageCode = "zh-Hans"
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = "flurry's Moments"
    signature = "不驰于空想，不骛于虚声。"
    cover = ""

    name = "Flurry"
    avatar = "/img/avatar.jpg"
